[build]
  base = "/"
  publish = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.16.0"

[functions]
  node_bundler = "esbuild"